# author: Bolt J Woofson
# from: https://github.com/

[colors.primary]
background = "#2B2B2B" #Midnight Granite
foreground = "#D8D8D8" #Nordic Mist

[colors.normal]
black   = "#2B2B2B" #Midnight Granite
red     = "#FF6F61" #Solar Veil
green   = "#5A7D6B" #Frosted Pine
yellow  = "#F4C542" #Nordic Gold
blue    = "#5E7A94" #Lunar Blue
magenta = "#A86BAD" #Heather Bloom
cyan    = "#7FFFB3" #Boreal Glow
white   = "#D8D8D8" #Nordic Mist

[colors.bright]
black   = "#52494E"
red     = "#FF4F58"
green   = "#73D936"
yellow  = "#FFDD33"
blue    = "#96A6C8"
magenta = "#AFAFD7"
cyan    = "#95A99F"
white   = "#F5F5F5"
