clear
pastel paint FAE2A2 --on 5B616A "  The Norwegian Moonstone Palette  "
pastel paint FAE2a2 --on 5B616A "           Light version           "
pastel paint 9aadbf --on 5E5E5E "  #5E5E5E Bergen Morning           "
pastel paint fae2a2 --on 5B616A "  #5B616A Dim Grey                 "
pastel paint 5e5e5e --on 9AADBF "  #9AADBF Cold Steel               "
pastel paint 5e5e5e --on A3AFBB "  #A3AFBB Steel                    "
pastel paint 5e5e5e --on BDBDBD "  #BDBDBD CrowSilver               "
pastel paint 5e5e5e --on E3E3E3 "  #E3E3E3 Wetfire                  "
pastel paint 519a78 --on FFFFFF "  #FFFFFF Snow                     "
pastel paint 5e5e5e --on EAF2F6 "  #EAF2F6 Whitesmoke               "
pastel paint 5e5e5e --on FFFFFF "  #FFFFFF Snow                     "
pastel paint 5e5e5e --on 8FAE9E "  #8FAE9E Lichen                   "
pastel paint f3dcb5 --on 519A78 "  #519A78 Arctic Herbs             "
pastel paint 5b616a --on D0F5E5 "  #D0F5E5 Dew                      "
pastel paint 5e5e5e --on E5FFEF "  #E5FFEF Dew                      "
pastel paint 5e5e5e --on F3DCB5 "  #F3DCB5 Wheat                    "
pastel paint 5e5e5e --on FAE2A2 "  #FAE2A2 Wheat                    "
pastel paint 5e5e5e --on DB968C "  #DB968C Dark Salmon              "
pastel paint 5e5e5e --on FFCCC7 "  #FFCCC7 Arctic Rose              "
pastel paint 5e5e5e --on CDA6C0 "  #CDA6C0 Thistle                  "
pastel paint 5e5e5e --on CEADD1 "  #CEADD1 Thistle II               "

